"""Built-in metric collectors for chaos-jungle."""

from __future__ import annotations
import fnmatch
import os
import re
from typing import Callable

from chaos_jungle.metrics.base import Metric
from chaos_jungle.targets.base import Target


class PingLatency(Metric):
    """Measure round-trip latency by running ``ping`` on the target.

    Parses average, minimum, and maximum RTT from the ping output.
    Works on any target (local, SSH, or HTTP) that can execute ``ping``.

    Parameters
    ----------
    host : str
        Hostname or IP to ping. Default ``"127.0.0.1"``.
    count : int
        Number of ping packets to send. Default ``5``.
    name : str
        Key prefix in results. Default ``"ping"``.

    Examples
    --------
    .. code-block:: python

        from chaos_jungle.metrics import PingLatency

        metric = PingLatency("8.8.8.8", count=5)
        # results: {"avg_ms": 12.3, "min_ms": 10.1, "max_ms": 15.2, "samples": 5}
    """

    def __init__(
        self,
        host: str = "127.0.0.1",
        count: int = 5,
        name: str = "ping",
    ) -> None:
        self.host = host
        self.count = count
        self.name = name

    def collect(self, target: Target) -> dict:
        _, out, _ = target.run(
            f"ping -c {self.count} -W 2 {self.host} 2>/dev/null"
        )
        times = []
        for line in out.splitlines():
            if "time=" in line:
                try:
                    times.append(float(line.split("time=")[1].split()[0]))
                except (IndexError, ValueError):
                    pass

        if not times:
            return {"avg_ms": None, "min_ms": None, "max_ms": None, "samples": 0}

        return {
            "avg_ms": round(sum(times) / len(times), 3),
            "min_ms": round(min(times), 3),
            "max_ms": round(max(times), 3),
            "samples": len(times),
        }


class CommandMetric(Metric):
    """Run an arbitrary shell command and parse its output into a dict.

    Parameters
    ----------
    cmd : str
        Shell command to run on the target.
    parse : callable
        Function that takes the stdout string and returns a ``dict``.
        If it raises or returns ``None``, an empty dict is used.
    name : str
        Key prefix in results.

    Examples
    --------
    .. code-block:: python

        from chaos_jungle.metrics import CommandMetric

        # measure CPU idle %
        cpu = CommandMetric(
            "top -bn1 | grep 'Cpu(s)' | awk '{print $8}'",
            parse=lambda out: {"idle_pct": float(out.strip())},
            name="cpu",
        )

        # measure disk usage %
        disk = CommandMetric(
            "df / | tail -1 | awk '{print $5}'",
            parse=lambda out: {"used_pct": int(out.strip().rstrip('%'))},
            name="disk",
        )
    """

    def __init__(
        self,
        cmd: str,
        parse: Callable[[str], dict],
        name: str = "cmd",
    ) -> None:
        self.cmd = cmd
        self.parse = parse
        self.name = name

    def collect(self, target: Target) -> dict:
        _, out, _ = target.run(self.cmd)
        try:
            result = self.parse(out)
            return result if isinstance(result, dict) else {}
        except Exception:
            return {}


class FileIntegrity(Metric):
    """Count files matching a pattern and detect missing or corrupted ones.

    Runs ``find`` on the target to enumerate files, then checks each one
    against an optional reference checksum file. Useful alongside
    :class:`~chaos_jungle.faults.storage.StorageCorrupt` to measure how
    many files were bit-flipped.

    Parameters
    ----------
    pattern : str
        Glob pattern, e.g. ``"*.pdb"``.
    directory : str
        Directory to scan on the target.
    checksum_file : str, optional
        Path to a reference MD5 checksum file (generated by
        ``md5sum <files> > ref.md5``). If given, each file is verified
        against it and ``corrupted`` count is set accordingly.
    name : str
        Key prefix in results. Default ``"integrity"``.

    Examples
    --------
    .. code-block:: python

        from chaos_jungle.metrics import FileIntegrity

        # just count files
        m = FileIntegrity("*.pdb", "/scratch/data")
        # results: {"files_found": 500, "files_missing": 0, "files_corrupted": 0}

        # verify against a reference checksum
        m = FileIntegrity("*.pdb", "/scratch/data",
                          checksum_file="/scratch/ref.md5")
    """

    def __init__(
        self,
        pattern: str,
        directory: str,
        checksum_file: str | None = None,
        name: str = "integrity",
    ) -> None:
        self.pattern = pattern
        self.directory = directory
        self.checksum_file = checksum_file
        self.name = name

    def collect(self, target: Target) -> dict:
        # count matching files
        _, out, _ = target.run(
            f"find {self.directory} -name '{self.pattern}' -type f 2>/dev/null | wc -l"
        )
        try:
            files_found = int(out.strip())
        except ValueError:
            files_found = 0

        corrupted = 0
        if self.checksum_file:
            _, chk_out, _ = target.run(
                f"md5sum --check {self.checksum_file} 2>/dev/null | grep FAILED | wc -l"
            )
            try:
                corrupted = int(chk_out.strip())
            except ValueError:
                corrupted = 0

        return {
            "files_found": files_found,
            "files_corrupted": corrupted,
        }


class ThroughputMetric(Metric):
    """Measure network throughput using ``curl`` to download a test URL.

    Runs a timed ``curl`` transfer and extracts the average download
    speed reported by curl's built-in statistics.

    Parameters
    ----------
    url : str
        URL to download for measurement.
    name : str
        Key prefix in results. Default ``"throughput"``.

    Examples
    --------
    .. code-block:: python

        from chaos_jungle.metrics import ThroughputMetric

        m = ThroughputMetric("http://storage-node/testfile.dat")
        # results: {"speed_mbps": 42.1, "time_s": 2.3}
    """

    def __init__(self, url: str, name: str = "throughput") -> None:
        self.url = url
        self.name = name

    def collect(self, target: Target) -> dict:
        _, out, _ = target.run(
            f"curl -o /dev/null -s -w '%{{speed_download}} %{{time_total}}' {self.url}"
        )
        parts = out.strip().split()
        if len(parts) < 2:
            return {"speed_mbps": None, "time_s": None}
        try:
            speed_bps = float(parts[0])
            time_s = float(parts[1])
            return {
                "speed_mbps": round(speed_bps / 1_000_000, 3),
                "time_s": round(time_s, 3),
            }
        except ValueError:
            return {"speed_mbps": None, "time_s": None}
